import type { SessionActivity } from '../../core/fold'

/**
 * Shared template pieces. Projections are generated files — the header
 * makes hand-editing them a visible bug (BD5).
 */
export const GENERATED_HEADER =
  '<!-- generated by sofar — do not hand-edit; truth lives in events.jsonl -->'

/** The "+N more" sentinel the fold appends when an activity list hits its cap (BD44). */
const MORE_SENTINEL = /^\+(\d+) more$/

/**
 * One-line rendering of derived session activity (task 7.2, BD44):
 * "N files (a, b, +K more), M commands, task changes: 1.2 → done". The file
 * count includes sentinel overflow so it states the true unique-path total.
 */
export function describeActivity(activity: SessionActivity): string {
  const parts: string[] = []
  if (activity.files.length > 0) {
    const more = MORE_SENTINEL.exec(activity.files[activity.files.length - 1]!)
    const count = more !== null ? activity.files.length - 1 + Number(more[1]) : activity.files.length
    parts.push(`${count} file${count === 1 ? '' : 's'} (${activity.files.join(', ')})`)
  }
  if (activity.commands > 0) {
    parts.push(`${activity.commands} command${activity.commands === 1 ? '' : 's'}`)
  }
  if (activity.task_changes.length > 0) {
    parts.push(`task changes: ${activity.task_changes.join(', ')}`)
  }
  return parts.length > 0 ? parts.join(', ') : '(no mechanical events)'
}

/** Join non-empty template sections into a document with a trailing newline. */
export function doc(lines: readonly string[]): string {
  return lines.join('\n').replace(/\n+$/, '') + '\n'
}

/**
 * Truncation-aware clip result (staleness-detection 1.3): budgeted sections
 * that want to KNOW they were cut — the mechanical clipped-summary signal —
 * use the *Detect variants; `clipped` is true only when the budget forced a
 * cut. Detection lives at the render seam because budgets do.
 */
export interface ClipResult {
  text: string
  clipped: boolean
}

/** clip(), reporting whether it cut. */
export function clipDetect(text: string, max: number): ClipResult {
  const oneLine = text.replace(/\s+/g, ' ').trim()
  if (oneLine.length <= max) return { text: oneLine, clipped: false }
  return { text: `${oneLine.slice(0, Math.max(0, max - 1))}…`, clipped: true }
}

/**
 * Collapse whitespace and hard-cap a string's length (budgeted sections of
 * the status projection — BD24). The ellipsis is inside the budget.
 */
export function clip(text: string, max: number): string {
  return clipDetect(text, max).text
}

/**
 * Multi-line budget clip for hand-written blocks, reporting whether it cut:
 * unlike clip() it preserves line structure (e.g. repo.md is prose the
 * author formatted); the truncation marker lands INSIDE the budget so the
 * section total never exceeds it.
 */
export function clipBlockDetect(text: string, budget: number, marker: string): ClipResult {
  const trimmed = text.trim()
  if (trimmed.length <= budget) return { text: trimmed, clipped: false }
  const suffix = `\n${marker}`
  return {
    text: `${trimmed.slice(0, Math.max(0, budget - suffix.length)).trimEnd()}${suffix}`,
    clipped: true,
  }
}

/** Task-level progress across phases: [done, total]. */
export function taskProgress(phases: ReadonlyArray<{ tasks: ReadonlyArray<{ status: string }> }>): [number, number] {
  let done = 0
  let total = 0
  for (const phase of phases) {
    for (const task of phase.tasks) {
      total += 1
      if (task.status === 'done') done += 1
    }
  }
  return [done, total]
}

/** Percentage string that never claims 100% while work remains. */
export function pct(done: number, total: number): string {
  if (total === 0) return '0%'
  const raw = Math.floor((done / total) * 100)
  return `${done === total ? 100 : Math.min(raw, 99)}%`
}
