/**
 * Shared template pieces. Projections are generated files — the header
 * makes hand-editing them a visible bug (BD5).
 */
export const GENERATED_HEADER =
  '<!-- generated by harness — do not hand-edit; truth lives in events.jsonl -->'

/** Join non-empty template sections into a document with a trailing newline. */
export function doc(lines: readonly string[]): string {
  return lines.join('\n').replace(/\n+$/, '') + '\n'
}
