import type { FreshnessState, SessionActivity } from '../../core/fold'

/**
 * Shared template pieces. Projections are generated files — the header
 * makes hand-editing them a visible bug (BD5).
 */
export const GENERATED_HEADER =
  '<!-- generated by sofar — do not hand-edit; truth lives in events.jsonl -->'

/** The "+N more" sentinel the fold appends when an activity list hits its cap (BD44). */
const MORE_SENTINEL = /^\+(\d+) more$/

/**
 * One-line rendering of derived session activity (task 7.2, BD44):
 * "N files (a, b, +K more), M commands, task changes: 1.2 → done". The file
 * count includes sentinel overflow so it states the true unique-path total.
 */
export function describeActivity(activity: SessionActivity): string {
  const parts: string[] = []
  if (activity.files.length > 0) {
    const more = MORE_SENTINEL.exec(activity.files[activity.files.length - 1]!)
    const count = more !== null ? activity.files.length - 1 + Number(more[1]) : activity.files.length
    parts.push(`${count} file${count === 1 ? '' : 's'} (${activity.files.join(', ')})`)
  }
  if (activity.commands > 0) {
    parts.push(`${activity.commands} command${activity.commands === 1 ? '' : 's'}`)
  }
  if (activity.task_changes.length > 0) {
    parts.push(`task changes: ${activity.task_changes.join(', ')}`)
  }
  return parts.length > 0 ? parts.join(', ') : '(no mechanical events)'
}

/**
 * One-line breakdown of the freshness counters (staleness-detection 2.1):
 * "3 files, 2 commands, 1 task change" — zero-count kinds are omitted.
 * Shared by renderStatus (budgeted line) and renderFullStatus (uncapped
 * staleness section) so both surfaces state the same drift.
 */
export function describeFreshness(counts: FreshnessState['events_since_writeback']): string {
  const n = (count: number, noun: string, plural = `${noun}s`) =>
    `${count} ${count === 1 ? noun : plural}`
  const parts: string[] = []
  if (counts.files > 0) parts.push(n(counts.files, 'file'))
  if (counts.commands > 0) parts.push(n(counts.commands, 'command'))
  if (counts.tasks > 0) parts.push(n(counts.tasks, 'task change'))
  if (counts.notes > 0) parts.push(n(counts.notes, 'note'))
  if (counts.decisions > 0) parts.push(n(counts.decisions, 'decision'))
  if (counts.memories > 0) parts.push(n(counts.memories, 'promoted memory', 'promoted memories'))
  return parts.join(', ')
}

/** Join non-empty template sections into a document with a trailing newline. */
export function doc(lines: readonly string[]): string {
  return lines.join('\n').replace(/\n+$/, '') + '\n'
}

/**
 * Truncation-aware clip result (staleness-detection 1.3): budgeted sections
 * that want to KNOW they were cut — the mechanical clipped-summary signal —
 * use the *Detect variants; `clipped` is true only when the budget forced a
 * cut. Detection lives at the render seam because budgets do.
 */
export interface ClipResult {
  text: string
  clipped: boolean
}

/** clip(), reporting whether it cut. */
export function clipDetect(text: string, max: number): ClipResult {
  const oneLine = text.replace(/\s+/g, ' ').trim()
  if (oneLine.length <= max) return { text: oneLine, clipped: false }
  return { text: `${oneLine.slice(0, Math.max(0, max - 1))}…`, clipped: true }
}

/**
 * Collapse whitespace and hard-cap a string's length (budgeted sections of
 * the status projection — BD24). The ellipsis is inside the budget.
 */
export function clip(text: string, max: number): string {
  return clipDetect(text, max).text
}

/**
 * Multi-line budget clip for hand-written blocks, reporting whether it cut:
 * unlike clip() it preserves line structure (e.g. repo.md is prose the
 * author formatted); the truncation marker lands INSIDE the budget so the
 * section total never exceeds it.
 */
export function clipBlockDetect(text: string, budget: number, marker: string): ClipResult {
  const trimmed = text.trim()
  if (trimmed.length <= budget) return { text: trimmed, clipped: false }
  const suffix = `\n${marker}`
  return {
    text: `${trimmed.slice(0, Math.max(0, budget - suffix.length)).trimEnd()}${suffix}`,
    clipped: true,
  }
}

/**
 * Task-level progress across phases (task-drop-state D1).
 *
 * `dropped` is its own term, folded into neither side: counting drops as
 * `done` would inflate the numerator and claim delivery for work nobody
 * built, while quietly subtracting them from `total` would let an
 * initiative reach 100% by dropping its hard half, with the lost scope
 * leaving no trace. So the denominator holds every task ever planned and
 * callers surface the drop count next to it.
 */
export interface TaskProgress {
  done: number
  dropped: number
  /** Every task, drops included — this never shrinks silently. */
  total: number
  /** Genuinely outstanding: total − done − dropped. */
  remaining: number
}

export function taskProgress(
  phases: ReadonlyArray<{ tasks: ReadonlyArray<{ status: string }> }>,
): TaskProgress {
  let done = 0
  let dropped = 0
  let total = 0
  for (const phase of phases) {
    for (const task of phase.tasks) {
      total += 1
      if (task.status === 'done') done += 1
      else if (task.status === 'dropped') dropped += 1
    }
  }
  return { done, dropped, total, remaining: total - done - dropped }
}

/**
 * The headline progress sentence. Without drops this is byte-identical to
 * what it has always been — the injected digest's token budget depends on
 * the common case not growing. With drops it switches to the three-term
 * form, where "0 remaining" is the completion signal that `N/T done` can
 * no longer give honestly.
 */
export function progressText(p: TaskProgress): string {
  if (p.dropped === 0) return `${p.done}/${p.total} tasks done (${pct(p.done, p.total)})`
  return `${p.done} done, ${p.dropped} dropped, ${p.remaining} remaining`
}

/**
 * Compact headline for the width-constrained CLI zooms: `9/10 tasks (90%)`,
 * or `9/10 tasks, 1 dropped (100%)`. The percentage counts drops as
 * resolved, so it agrees with the pie beside it.
 */
export function progressCompact(p: TaskProgress): string {
  const drops = p.dropped === 0 ? '' : `, ${p.dropped} dropped`
  return `${p.done}/${p.total} tasks${drops} (${pct(p.done, p.total, p.dropped)})`
}

/** Compact per-phase fraction: `1/2`, or `1/3 (1 dropped)` when any was. */
export function phaseFraction(p: TaskProgress): string {
  const base = `${p.done}/${p.total}`
  return p.dropped === 0 ? base : `${base} (${p.dropped} dropped)`
}

/**
 * Percentage string that never claims 100% while work remains. Drops count
 * as resolved here — with nothing outstanding the number must be able to
 * reach 100%, which is the whole complaint that motivated this initiative.
 */
export function pct(done: number, total: number, dropped = 0): string {
  if (total === 0) return '0%'
  const resolved = done + dropped
  const raw = Math.floor((resolved / total) * 100)
  return `${resolved === total ? 100 : Math.min(raw, 99)}%`
}
