//! The status projection (rust-core 2.4) — `projections/templates/status.ts`
//! ported verbatim: [`render_status`] is the `SessionStart` block and the
//! `sofar_get_state` digest under its hard 10,000-unit cap; [`render_full_status`]
//! is plain `sofar status`, uncapped (`docs/HOTPATH.md` §Status block
//! (`renderStatus`) and full status; rust-core D14). The cross-session
//! derivations the templates read (`core/fold.ts`, Phase 11) live here too.
//! Every budget is UTF-16 units and every whitespace rule is JavaScript's (D2).

use crate::fold::{
    DecisionState, InitiativeState, PhaseState, RunState, SessionState, TaskState, freshness_total,
};
use crate::git::GitState;
use crate::json::{Json, js_to_string};
use crate::projections::{
    clip, clip_block_detect, clip_detect, describe_activity, describe_freshness, describe_run,
    phase_fraction, plural, progress_text, retired_ordinals, standing_constraint_lines,
    task_progress, test_outcome_line,
};
use crate::text::{
    cmp_utf16, date_part, is_js_whitespace, js_trim, one_line, utf16_len, utf16_prefix,
};

pub const STATUS_CHAR_LIMIT: usize = 10_000;
pub const STATUS_TRUNCATION_MARKER: &str = "…truncated — run sofar status for full detail";
pub const REPO_MEMORY_CHAR_BUDGET: usize = 1_500;
pub const REPO_MEMORY_TRUNCATION_MARKER: &str = "…truncated — read .sofar/repo.md for the rest";

const SESSION_ID_BUDGET: usize = 120;
const GOAL_BUDGET: usize = 600;
const TASK_LINE_BUDGET: usize = 200;
const NEXT_ACTION_BUDGET: usize = 500;
const BLOCKED_BUDGET: usize = 500;
const PHASE_LINE_BUDGET: usize = 100;
const MAX_PHASE_LINES: usize = 12;
const DONE_PHASES_LINE_BUDGET: usize = 220;
const SESSION_SUMMARY_BUDGET: usize = 1_200;
const DERIVED_SESSION_BUDGET: usize = 600;
const DECISION_CHOSE_BUDGET: usize = 120;
const DECISION_RULED_CHOSE_BUDGET: usize = 60;
const MAX_DECISIONS: usize = 5;
const REJECTED_OVER_LINE_BUDGET: usize = 90;
const REJECTED_LEDGER_BUDGET: i64 = 2_800;
const PROTOCOL_TAIL_RESERVE: i64 = 400;
const STANDING_LEDGER_BUDGET: usize = 2_000;
const CONFLICT_LINE_BUDGET: usize = 200;
const MAX_CONFLICT_LINES: usize = 8;
const STALENESS_LINE_BUDGET: usize = 200;
const PARALLEL_LINE_BUDGET: usize = 260;
const MAX_PARALLEL_LINES: usize = 3;
const NOTE_LINE_BUDGET: usize = 200;
const MAX_NOTES: usize = 5;
const TASK_FILES_LINE_BUDGET: usize = 300;
const MAX_TASK_FILES: usize = 8;
const NEIGHBOUR_LINE_BUDGET: usize = 200;
const MAX_NEIGHBOURS: usize = 3;
const DRIVEN_LINE_BUDGET: usize = 300;
/// Cap on the sibling-count line (record-integrity 4.3).
pub const UNWRITTEN_SIBLING_CAP: usize = 5;

/// The quick-work lane's slug (`core/lane.ts`, r1-fixes 2.6, D14).
pub const QUICK_LANE: &str = "quick";
/// How many recent lane sessions the `SessionStart` block names.
pub const LANE_RECENT_SESSIONS: usize = 5;

const LANE_HOW_LINES: [&str; 3] = [
    "This branch is bound to no initiative, so the hooks capture edits and commands here — no sofar new, no plan, no write-back.",
    "- Made a decision? sofar_start_session (id below) then sofar_log_decision — one line of why. That is the only ask.",
    "- Project-sized work needs its own record: sofar new <slug> --goal \"<one line>\" (or sofar switch <slug>) — this session follows the branch there.",
];

const READ_BACK_LINE: &str = "Read-back: before acting, restate goal, next action, and standing constraints in one sentence each — if your restatement disagrees with this block, trust the block and say so.";
const FOOTER_LINE: &str = "(generated by sofar — full detail in plan.md, decisions.md, sessions/)";

// ---------------------------------------------------------------------------
// Schema predicates (packages/schema/src/events.ts)

/// `isClosedInitiativeStatus`: done | dropped | superseded.
#[must_use]
pub fn is_closed_initiative_status(s: &str) -> bool {
    matches!(s, "done" | "dropped" | "superseded")
}

/// `isResolvedTaskStatus`: done | dropped.
#[must_use]
pub fn is_resolved_task_status(s: &str) -> bool {
    matches!(s, "done" | "dropped")
}

// ---------------------------------------------------------------------------
// Cross-session derivations (core/fold.ts, Phase 11 / D-P11)

/// A file path touched by more than one still-open session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileConflict {
    pub path: String,
    pub sessions: Vec<String>,
}

/// A phase whose tasks are all resolved but that was never closed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StalePhase {
    pub name: String,
    pub status: String,
    pub tasks_done: usize,
}

/// A concurrent session's write-back that lost the `next_action` scalar (task 12.4).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParallelWriteback {
    pub session_id: String,
    pub tool: String,
    pub ended: String,
    pub next_action: String,
}

/// `latestRun`.
#[must_use]
pub fn latest_run(state: &InitiativeState) -> Option<&RunState> {
    state.runs.last()
}

/// `openSessionFiles`: (session, file) pairs of every live session's activity,
/// the `+N more` sentinel skipped.
#[must_use]
pub fn open_session_files<'a>(
    state: &'a InitiativeState,
    also_live: Option<&str>,
) -> Vec<(&'a str, &'a str)> {
    let mut pairs = Vec::new();
    for session in &state.sessions {
        let live = session.ended.is_none() || also_live == Some(session.id.as_str());
        let Some(activity) = &session.activity else {
            continue;
        };
        if !live {
            continue;
        }
        for file in &activity.files {
            if file.starts_with('+') {
                continue;
            }
            pairs.push((session.id.as_str(), file.as_str()));
        }
    }
    pairs
}

/// `openSessionFileConflicts`: files ≥2 open sessions touched, sorted by
/// path in UTF-16 code-unit order (rust-core D6).
#[must_use]
pub fn open_session_file_conflicts(
    state: &InitiativeState,
    also_live: Option<&str>,
) -> Vec<FileConflict> {
    let mut by_file: Vec<(&str, Vec<String>)> = Vec::new();
    for (session, file) in open_session_files(state, also_live) {
        match by_file.iter_mut().find(|(f, _)| *f == file) {
            Some(slot) => slot.1.push(session.to_owned()),
            None => by_file.push((file, vec![session.to_owned()])),
        }
    }
    let mut conflicts: Vec<FileConflict> = by_file
        .into_iter()
        .filter(|(_, sessions)| sessions.len() >= 2)
        .map(|(path, sessions)| FileConflict {
            path: path.to_owned(),
            sessions,
        })
        .collect();
    conflicts.sort_by(|a, b| cmp_utf16(&a.path, &b.path));
    conflicts
}

/// `overlappingWritebacks`: the wrapped sessions whose `next_action` lost the
/// last-writer race against the reference (the newest write-back, or the
/// named one), newest first.
#[must_use]
pub fn overlapping_writebacks(
    state: &InitiativeState,
    reference_session_id: Option<&str>,
) -> Vec<ParallelWriteback> {
    fn ended(s: &SessionState) -> &str {
        s.ended.as_deref().expect("wrapped")
    }
    fn next(s: &SessionState) -> &str {
        s.next_action.as_deref().expect("wrapped")
    }
    let wrapped: Vec<&SessionState> = state
        .sessions
        .iter()
        .filter(|s| s.ended.is_some() && s.next_action.is_some())
        .collect();
    if wrapped.len() < 2 {
        return Vec::new();
    }
    let mut reference: Option<&SessionState> =
        reference_session_id.and_then(|id| wrapped.iter().copied().find(|s| s.id == id));
    if reference.is_none() {
        let mut best = wrapped[0];
        for s in &wrapped {
            if cmp_utf16(ended(s), ended(best)).is_ge() {
                best = s;
            }
        }
        reference = Some(best);
    }
    let r = reference.expect("set above");
    let mut out: Vec<&SessionState> = wrapped
        .iter()
        .copied()
        .filter(|s| {
            !std::ptr::eq(*s, r)
                && next(s) != next(r)
                && cmp_utf16(&s.started, ended(r)).is_le()
                && cmp_utf16(ended(s), &r.started).is_ge()
        })
        .collect();
    out.sort_by(|a, b| cmp_utf16(ended(b), ended(a)));
    out.into_iter()
        .map(|s| ParallelWriteback {
            session_id: s.id.clone(),
            tool: s.tool.clone(),
            ended: ended(s).to_owned(),
            next_action: next(s).to_owned(),
        })
        .collect()
}

/// `staleActivePhases` (staleness-detection 1.2).
#[must_use]
pub fn stale_active_phases(state: &InitiativeState) -> Vec<StalePhase> {
    state
        .phases
        .iter()
        .filter(|p| p.status != "done" && p.status != "dropped" && !p.tasks.is_empty())
        .filter(|p| p.tasks.iter().all(|t| is_resolved_task_status(&t.status)))
        .map(|p| StalePhase {
            name: p.name.clone(),
            status: p.status.clone(),
            tasks_done: p.tasks.len(),
        })
        .collect()
}

// ---------------------------------------------------------------------------
// status.ts helpers

/// `enforceStatusLimit`: anything over the limit is cut to fit, marker included.
#[must_use]
pub fn enforce_status_limit(text: &str) -> String {
    if utf16_len(text) <= STATUS_CHAR_LIMIT {
        return text.to_owned();
    }
    let marker = format!("\n{STATUS_TRUNCATION_MARKER}\n");
    format!(
        "{}{marker}",
        utf16_prefix(text, STATUS_CHAR_LIMIT - utf16_len(&marker))
    )
}

fn last_with_summary(sessions: &[SessionState]) -> Option<&SessionState> {
    sessions.iter().rev().find(|s| s.summary.is_some())
}

/// `lastUnwrittenWithActivity`: newest → oldest, the first session with
/// activity but no summary, unless a written-back session is newer.
fn last_unwritten_with_activity(sessions: &[SessionState]) -> Option<&SessionState> {
    for session in sessions.iter().rev() {
        if session.summary.is_some() {
            return None;
        }
        if session.activity.is_some() {
            return Some(session);
        }
    }
    None
}

/// `unwrittenSessions`: EVERY session with activity and no summary, newest first.
#[must_use]
pub fn unwritten_sessions(sessions: &[SessionState]) -> Vec<&SessionState> {
    sessions
        .iter()
        .filter(|s| s.summary.is_none() && s.activity.is_some())
        .rev()
        .collect()
}

/// `hasRealAlternative`: `over` is non-blank and not the
/// `(no alternative …` / `(none …` placeholder — `/^\(\s*(no alternative|none)/i`,
/// a non-unicode regex, so the case fold is ASCII-only (P3).
fn has_real_alternative(over: &str) -> bool {
    let t = js_trim(over);
    if t.is_empty() {
        return false;
    }
    let Some(rest) = t.strip_prefix('(') else {
        return true;
    };
    let rest = rest.trim_start_matches(is_js_whitespace);
    let lower_starts = |needle: &str| {
        rest.len() >= needle.len()
            && rest.is_char_boundary(needle.len())
            && rest[..needle.len()].eq_ignore_ascii_case(needle)
    };
    !(lower_starts("no alternative") || lower_starts("none"))
}

const fn task_mark(status: &str) -> &'static str {
    match status.as_bytes() {
        b"done" => "[x]",
        b"active" => "[~]",
        b"blocked" => "[!]",
        b"dropped" => "[-]",
        _ => "[ ]",
    }
}

fn phase_mark(phase: &PhaseState, stale_names: &[&str]) -> String {
    if stale_names.contains(&phase.name.as_str()) {
        format!("[{} — all tasks done; mark phase done?]", phase.status)
    } else {
        format!("[{}]", phase.status)
    }
}

/// `taskTestsLine` (D24): the active task's latest test outcome, or the
/// at-least-as-new D19 verification.
fn task_tests_line(state: &InitiativeState, task: &TaskState) -> Option<String> {
    let test = state
        .task_tests
        .iter()
        .find(|(id, _)| *id == task.id)
        .map(|(_, t)| t);
    if let Some(v) = &task.verification
        && test.is_none_or(|t| cmp_utf16(&v.ts, &t.ts).is_ge())
    {
        return Some(format!("tests: verified {} — {}", v.result, v.command));
    }
    test.map(|t| format!("tests: {}", test_outcome_line(&t.outcome)))
}

/// `sessionIdLine`: the adopt-by-id line, or None for a missing/blank id.
#[must_use]
pub fn session_id_line(session_id: Option<&str>) -> Option<String> {
    let id = js_trim(session_id.unwrap_or(""));
    if id.is_empty() {
        return None;
    }
    Some(format!(
        "Session: {} — when calling sofar_start_session, pass this as session_id.",
        clip(id, SESSION_ID_BUDGET)
    ))
}

/// An adjacent record (record-index 3.3): another initiative that has worked
/// this one's files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NeighbourRecord {
    pub initiative: String,
    pub paths: u64,
    pub decisions: u64,
}

/// `StatusOptions` — what the `SessionStart` hook hands the template.
#[derive(Debug, Clone, PartialEq)]
pub struct StatusOptions {
    pub repo_memory: Option<String>,
    pub session_id: Option<String>,
    pub git: Option<GitState>,
    pub neighbours: Vec<NeighbourRecord>,
    pub notices: Vec<String>,
    pub lane: bool,
    /// `activity !== false`: the D24 test line. `None`/`Some(true)` render it.
    pub activity: Option<bool>,
    /// `retireEnabled()` (r1-fixes 3.2, D25): the TypeScript template reads
    /// `SOFAR_RETIRE` itself; here the caller passes it (templates read no
    /// env), defaulting to on.
    pub retire: bool,
}

impl Default for StatusOptions {
    fn default() -> Self {
        Self {
            repo_memory: None,
            session_id: None,
            git: None,
            neighbours: Vec::new(),
            notices: Vec::new(),
            lane: false,
            activity: None,
            retire: true,
        }
    }
}

/// `lines.join('\n').length`, signed because the ledger budget it feeds can go negative.
#[allow(
    clippy::cast_possible_wrap,
    reason = "a block is far below i64::MAX units"
)]
fn joined_len(lines: &[String]) -> i64 {
    if lines.is_empty() {
        return 0;
    }
    let units: usize = lines.iter().map(|l| utf16_len(l)).sum();
    (units + lines.len() - 1) as i64
}

#[allow(
    clippy::cast_possible_wrap,
    reason = "a line is far below i64::MAX units"
)]
fn units_i64(line: &str) -> i64 {
    utf16_len(line) as i64
}

const STATUS_CHAR_LIMIT_I64: i64 = 10_000;

fn goal_line(state: &InitiativeState) -> String {
    if state.goal.is_empty() {
        "(none recorded)".to_owned()
    } else {
        clip(&state.goal, GOAL_BUDGET)
    }
}

fn phase_head(name: &str) -> &str {
    name.split_once(" — ").map_or(name, |(head, _)| head)
}

/// `renderStatus`: the `SessionStart` block / `get_state` digest, ≤10,000 units.
#[must_use]
#[allow(clippy::too_many_lines, reason = "a verbatim port of one template")]
pub fn render_status(state: &InitiativeState, options: &StatusOptions) -> String {
    let mut lines: Vec<String> = Vec::new();
    let lane = options.lane;
    lines.push(if lane {
        format!(
            "# Sofar: quick-work lane ({})",
            if state.slug.is_empty() {
                QUICK_LANE
            } else {
                &state.slug
            }
        )
    } else {
        format!(
            "# Sofar status: {}",
            if state.slug.is_empty() {
                "(unnamed initiative)"
            } else {
                &state.slug
            }
        )
    });
    lines.push(String::new());
    lines.push(format!("Goal: {}", goal_line(state)));
    lines.push(String::new());
    if lane {
        lines.extend(LANE_HOW_LINES.iter().map(|l| (*l).to_owned()));
        lines.push(String::new());
    }

    // Retirement (r1-fixes 3.2, D25): a rule a later rule replaced, and below
    // a decision superseded or scoped to a task that resolved, leave the block.
    let retire = options.retire;
    let retired: Vec<usize> = if retire {
        retired_ordinals(state)
    } else {
        Vec::new()
    };
    let standing =
        standing_constraint_lines(&state.decisions, Some(STANDING_LEDGER_BUDGET), retire);
    if !standing.is_empty() {
        lines.extend(standing.iter().cloned());
        lines.push(String::new());
    }

    let repo_memory = js_trim(options.repo_memory.as_deref().unwrap_or(""));
    if !repo_memory.is_empty() {
        lines.push("Repo memory (.sofar/repo.md):".to_owned());
        lines.push(
            clip_block_detect(
                repo_memory,
                REPO_MEMORY_CHAR_BUDGET,
                REPO_MEMORY_TRUNCATION_MARKER,
            )
            .0,
        );
        lines.push(String::new());
    }

    let stale_phases = stale_active_phases(state);
    let stale_names: Vec<&str> = stale_phases.iter().map(|p| p.name.as_str()).collect();
    if !lane && !state.phases.is_empty() {
        let open: Vec<&PhaseState> = state
            .phases
            .iter()
            .filter(|p| p.status != "done" && p.status != "dropped")
            .collect();
        let done_phases: Vec<&PhaseState> =
            state.phases.iter().filter(|p| p.status == "done").collect();
        let dropped_phases: Vec<&PhaseState> = state
            .phases
            .iter()
            .filter(|p| p.status == "dropped")
            .collect();
        lines.push("Phases:".to_owned());
        for phase in open.iter().take(MAX_PHASE_LINES) {
            lines.push(format!(
                "- {} {} {}",
                clip(&phase.name, PHASE_LINE_BUDGET),
                phase_mark(phase, &stale_names),
                phase_fraction(task_progress([*phase]))
            ));
        }
        if open.len() > MAX_PHASE_LINES {
            lines.push(format!(
                "- …and {} more phases (see plan.md)",
                open.len() - MAX_PHASE_LINES
            ));
        }
        if !done_phases.is_empty() {
            let p = task_progress(done_phases.iter().copied());
            let names = done_phases
                .iter()
                .map(|ph| phase_head(&ph.name))
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(clip(
                &format!("- done: {names} ({}/{} tasks)", p.done, p.total),
                DONE_PHASES_LINE_BUDGET,
            ));
        }
        if !dropped_phases.is_empty() {
            let p = task_progress(dropped_phases.iter().copied());
            let names = dropped_phases
                .iter()
                .map(|ph| phase_head(&ph.name))
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(clip(
                &format!("- dropped: {names} ({} tasks)", p.total),
                DONE_PHASES_LINE_BUDGET,
            ));
        }
        lines.push(String::new());
    }

    if !lane {
        lines.push(format!(
            "Progress: {} across {} phase(s)",
            progress_text(task_progress(&state.phases)),
            state.phases.len()
        ));
    }

    let active = if lane {
        None
    } else {
        state
            .current
            .active_phase
            .as_deref()
            .and_then(|name| state.phases.iter().find(|p| p.name == name))
    };
    if let Some(active) = active {
        lines.push(format!(
            "Active phase: {} — {} tasks done",
            clip(&active.name, PHASE_LINE_BUDGET),
            phase_fraction(task_progress([active]))
        ));
        let current = active.tasks.iter().find(|t| t.status == "active");
        let next = active.tasks.iter().find(|t| t.status == "pending");
        if let Some(current) = current {
            lines.push(format!(
                "Current task: {}",
                clip(
                    &format!("{} {}", current.id, current.title),
                    TASK_LINE_BUDGET
                )
            ));
            if let Some((_, files)) = state.task_files.iter().find(|(id, _)| *id == current.id)
                && !files.is_empty()
            {
                let listed = files
                    .iter()
                    .take(MAX_TASK_FILES)
                    .map(String::as_str)
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "  {}",
                    clip(&format!("files: {listed}"), TASK_FILES_LINE_BUDGET - 2)
                ));
            }
            if options.activity != Some(false)
                && let Some(tests) = task_tests_line(state, current)
            {
                lines.push(format!("  {}", clip(&tests, TASK_FILES_LINE_BUDGET - 2)));
            }
        }
        if let Some(next) = next {
            lines.push(format!(
                "Next task: {}",
                clip(&format!("{} {}", next.id, next.title), TASK_LINE_BUDGET)
            ));
        }
    } else if !lane {
        lines.push("Active phase: (none)".to_owned());
    }

    if !lane && let Some(next_action) = &state.current.next_action {
        lines.push(format!(
            "Next action: {}",
            clip(next_action, NEXT_ACTION_BUDGET)
        ));
    }

    let parallel = if lane {
        Vec::new()
    } else {
        overlapping_writebacks(state, None)
    };
    if !parallel.is_empty() {
        lines.push(format!(
            "⚠ Parallel write-backs — {} overlapping session(s) also recorded a next action:",
            parallel.len()
        ));
        for w in parallel.iter().take(MAX_PARALLEL_LINES) {
            lines.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{}, ended {}: {}",
                        w.tool,
                        date_part(&w.ended),
                        w.next_action
                    ),
                    PARALLEL_LINE_BUDGET
                )
            ));
        }
        if parallel.len() > MAX_PARALLEL_LINES {
            lines.push(format!(
                "- …and {} more (run sofar status)",
                parallel.len() - MAX_PARALLEL_LINES
            ));
        }
    }

    let drift = freshness_total(&state.freshness);
    if !lane && drift > 0 && state.freshness.last_writeback_ts.is_some() {
        lines.push(clip(
            &format!(
                "⚠ next action may be stale: {drift} event{} since write-back ({})",
                if drift == 1 { "" } else { "s" },
                describe_freshness(&state.freshness.events_since_writeback)
            ),
            STALENESS_LINE_BUDGET,
        ));
    }

    let notes = &state.freshness.notes;
    if !notes.is_empty() {
        let recent = &notes[notes.len().saturating_sub(MAX_NOTES)..];
        let skipped = notes.len() - recent.len();
        let label = if state.freshness.last_writeback_ts.is_some() {
            "Notes since write-back"
        } else {
            "Notes"
        };
        lines.push(format!(
            "{label}{}:",
            if skipped > 0 {
                format!(" (last {} of {})", recent.len(), notes.len())
            } else {
                String::new()
            }
        ));
        for n in recent {
            lines.push(format!(
                "- {}",
                clip(
                    &format!("{} {}", date_part(&n.ts), n.text),
                    NOTE_LINE_BUDGET
                )
            ));
        }
    }

    if !lane && let Some(blocked) = &state.current.blocked_on {
        lines.push(format!("Blocked on: {}", clip(blocked, BLOCKED_BUDGET)));
    }

    let conflicts = open_session_file_conflicts(state, None);
    if !conflicts.is_empty() {
        lines.push(format!(
            "⚠ Concurrent edits — {} file(s) touched by multiple open sessions:",
            conflicts.len()
        ));
        for c in conflicts.iter().take(MAX_CONFLICT_LINES) {
            lines.push(format!(
                "- {}",
                clip(
                    &format!("{} (sessions {})", c.path, c.sessions.join(", ")),
                    CONFLICT_LINE_BUDGET
                )
            ));
        }
        if conflicts.len() > MAX_CONFLICT_LINES {
            lines.push(format!(
                "- …and {} more (run sofar doctor)",
                conflicts.len() - MAX_CONFLICT_LINES
            ));
        }
    }
    if !lane || !conflicts.is_empty() {
        lines.push(String::new());
    }

    let last = last_with_summary(&state.sessions);
    if let Some(last) = last {
        lines.push(format!(
            "Last session ({}, ended {}):",
            last.tool,
            last.ended.as_deref().unwrap_or("?")
        ));
        let summary_text = last.summary.as_deref().expect("has summary");
        let (summary, clipped) = clip_detect(summary_text, SESSION_SUMMARY_BUDGET);
        if clipped {
            let pointer = format!(
                " (clipped — full text in sessions/{}.md)",
                clip(&last.id, SESSION_ID_BUDGET)
            );
            lines.push(format!(
                "  {}{pointer}",
                clip(
                    summary_text,
                    SESSION_SUMMARY_BUDGET.saturating_sub(utf16_len(&pointer))
                )
            ));
        } else {
            lines.push(format!("  {summary}"));
        }
        lines.push(String::new());
    }

    if let Some(run) = latest_run(state) {
        lines.push(clip(
            &format!("Driven: {}", describe_run(run)),
            DRIVEN_LINE_BUDGET,
        ));
        lines.push(String::new());
    }

    if lane && !state.sessions.is_empty() {
        let worked: Vec<&SessionState> = state
            .sessions
            .iter()
            .filter(|s| s.activity.is_some())
            .rev()
            .collect();
        let since = state.sessions.first().map(|s| date_part(&s.started));
        lines.push(format!(
            "Recent quick work ({}, {}{}{}):",
            plural(state.sessions.len() as u64, "session"),
            plural(state.decisions.len() as u64, "decision"),
            since.map(|s| format!(" since {s}")).unwrap_or_default(),
            if worked.len() > LANE_RECENT_SESSIONS {
                format!("; last {LANE_RECENT_SESSIONS}")
            } else {
                String::new()
            }
        ));
        for s in worked.iter().take(LANE_RECENT_SESSIONS) {
            lines.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{} {} — {}",
                        date_part(&s.started),
                        s.tool,
                        describe_activity(s.activity.as_ref().expect("filtered"))
                    ),
                    DERIVED_SESSION_BUDGET
                )
            ));
        }
        lines.push(String::new());
    }

    let unwritten = if lane {
        None
    } else {
        last_unwritten_with_activity(&state.sessions)
    };
    if let Some(u) = unwritten {
        let fate = if u.ended.is_some() {
            "ended without write-back"
        } else {
            "open, no write-back yet"
        };
        let closed = u
            .closed_reason
            .as_ref()
            .map(|r| format!(", closed: {r}"))
            .unwrap_or_default();
        lines.push(clip(
            &format!(
                "Last session ({}{closed}) {fate} — derived: {}",
                u.tool,
                describe_activity(u.activity.as_ref().expect("has activity"))
            ),
            DERIVED_SESSION_BUDGET,
        ));
        lines.push(format!(
            "  (details in sessions/{}.md)",
            clip(&u.id, SESSION_ID_BUDGET)
        ));
        lines.push(String::new());
    }

    let all_unwritten = if lane {
        Vec::new()
    } else {
        unwritten_sessions(&state.sessions)
    };
    let others: Vec<&SessionState> = all_unwritten
        .into_iter()
        .filter(|s| unwritten.is_none_or(|u| u.id != s.id))
        .collect();
    if !others.is_empty() {
        let named: Vec<String> = others
            .iter()
            .take(UNWRITTEN_SIBLING_CAP)
            .map(|s| clip(&s.id, SESSION_ID_BUDGET))
            .collect();
        let more = if others.len() > named.len() {
            format!(", +{} more", others.len() - named.len())
        } else {
            String::new()
        };
        lines.push(clip(
            &format!(
                "⚠ {} other session(s) did work without writing back: {}{more}",
                others.len(),
                named.join(", ")
            ),
            DERIVED_SESSION_BUDGET,
        ));
        lines.push(String::new());
    }

    // The volatile tail (D12), built before the decision index so the ledger
    // can reserve its real length.
    let mut tail: Vec<String> = Vec::new();
    let neighbours = &options.neighbours;
    if !neighbours.is_empty() {
        let named = &neighbours[..neighbours.len().min(MAX_NEIGHBOURS)];
        let decisions: u64 = neighbours.iter().map(|n| n.decisions).sum();
        tail.push(format!(
            "Adjacent records — {} across {} that have worked this one's files, densest first:",
            plural(decisions, "decision"),
            plural(neighbours.len() as u64, "other initiative")
        ));
        for n in named {
            tail.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{} — {}, {}",
                        n.initiative,
                        plural(n.paths, "shared file"),
                        plural(n.decisions, "decision")
                    ),
                    NEIGHBOUR_LINE_BUDGET
                )
            ));
        }
        let rest = neighbours.len() - named.len();
        tail.push(format!(
            "{}Adjacency, not aboutness — offered as worth reading, never as a rule.",
            if rest > 0 {
                format!("…and {rest} more. ")
            } else {
                String::new()
            }
        ));
        tail.push(String::new());
    }

    let id_line = session_id_line(options.session_id.as_deref());
    if let Some(line) = &id_line {
        tail.push(line.clone());
    }
    if let Some(git) = &options.git {
        let sync = match &git.upstream {
            None => "no origin ref — never pushed".to_owned(),
            Some(_) if git.synced => format!("in sync with origin/{}", git.branch),
            Some(upstream) => format!(
                "differs from origin/{} ({upstream}) — unpushed work",
                git.branch
            ),
        };
        tail.push(format!(
            "Git: {}",
            clip(
                &format!("{} @ {} — {sync}", git.branch, git.head),
                GOAL_BUDGET
            )
        ));
    }
    if id_line.is_some() || options.git.is_some() {
        tail.push(String::new());
    }

    for notice in options.notices.iter().filter(|n| !js_trim(n).is_empty()) {
        tail.push(notice.clone());
        tail.push(String::new());
    }

    if !state.decisions.is_empty() {
        // In-force decisions keep their ordinals (D25: ids never renumber);
        // the window is the last 5 of THEM.
        let in_force: Vec<(usize, &DecisionState)> = state
            .decisions
            .iter()
            .enumerate()
            .map(|(i, d)| (i + 1, d))
            .filter(|(ordinal, _)| !retired.contains(ordinal))
            .collect();
        let recent = &in_force[in_force.len().saturating_sub(MAX_DECISIONS)..];
        let older_count = in_force.len() - recent.len();
        let shown_rules: Vec<usize> = standing
            .iter()
            .filter_map(|line| {
                let digits = line.strip_prefix("- [D")?;
                let end = digits.find(']')?;
                digits[..end].parse().ok()
            })
            .collect();
        let count = if older_count > 0 {
            format!("last {} of {}", recent.len(), in_force.len())
        } else {
            in_force.len().to_string()
        };
        let window = if retired.is_empty() {
            count
        } else {
            format!("{count} in force, {} retired", retired.len())
        };
        lines.push(format!(
            "Recent decisions ({window}; full text in decisions.md):"
        ));
        for (ordinal, d) in recent {
            let ordinal = *ordinal;
            let ruled = d.rule.is_some() && shown_rules.contains(&ordinal);
            let chose = clip(
                &d.chose,
                if ruled {
                    DECISION_RULED_CHOSE_BUDGET
                } else {
                    DECISION_CHOSE_BUDGET
                },
            );
            let over = if has_real_alternative(&d.over) {
                format!(" — over {}", clip(&d.over, REJECTED_OVER_LINE_BUDGET))
            } else {
                String::new()
            };
            let mut marks: Vec<String> = Vec::new();
            if ruled {
                marks.push("rule above".to_owned());
            }
            if retire && let Some(supersedes) = &d.supersedes {
                marks.push(format!("supersedes {supersedes}"));
            }
            let mark = if marks.is_empty() {
                String::new()
            } else {
                format!(" ({})", marks.join("; "))
            };
            lines.push(format!(
                "- [D{ordinal}] {}{mark} {chose}{over}",
                date_part(&d.ts)
            ));
        }

        let rejected: Vec<(usize, &DecisionState)> = in_force[..older_count]
            .iter()
            .copied()
            .filter(|(_, d)| has_real_alternative(&d.over))
            .collect();
        if !rejected.is_empty() {
            lines.push(format!(
                "Earlier rejected approaches — do NOT re-propose ({} older):",
                rejected.len()
            ));
            let ledger_budget = REJECTED_LEDGER_BUDGET.min(
                STATUS_CHAR_LIMIT_I64
                    - joined_len(&lines)
                    - joined_len(&tail)
                    - PROTOCOL_TAIL_RESERVE,
            );
            let mut used: i64 = 0;
            let mut shown = 0;
            for (ordinal, d) in &rejected {
                let entry = format!(
                    "- [D{ordinal}] {}",
                    clip(&d.over, REJECTED_OVER_LINE_BUDGET)
                );
                let len = units_i64(&entry);
                if used + len + 1 > ledger_budget {
                    break;
                }
                lines.push(entry);
                used += len + 1;
                shown += 1;
            }
            if shown < rejected.len() {
                lines.push(format!(
                    "- …and {} more (see decisions.md)",
                    rejected.len() - shown
                ));
            }
        }
        lines.push(String::new());
    }

    if !state.decisions.is_empty() || !state.memories.is_empty() {
        lines.push(format!(
            "Next ids: D{} (decision), M{} (memory)",
            state.decisions.len() + 1,
            state.memories.len() + 1
        ));
        lines.push(String::new());
    }

    lines.extend(tail);

    if !lane && (state.current.next_action.is_some() || !standing.is_empty()) {
        lines.push(READ_BACK_LINE.to_owned());
        lines.push(String::new());
    }

    lines.push(FOOTER_LINE.to_owned());
    let joined = lines.join("\n");
    enforce_status_limit(&format!("{}\n", joined.trim_end_matches('\n')))
}

/// A string field of the run surface, as `${s.x}` prints it (`undefined` when absent).
fn surface_field(surface: &Json, key: &str) -> Option<String> {
    surface.as_obj()?.get(key).map(js_to_string)
}

fn surface_list(surface: &Json, key: &str) -> Vec<String> {
    surface
        .as_obj()
        .and_then(|o| o.get(key))
        .and_then(Json::as_arr)
        .map(|items| items.iter().map(js_to_string).collect())
        .unwrap_or_default()
}

/// `renderFullStatus`: plain `sofar status`, uncapped, with the per-task tree.
/// `retire` is `retireEnabled()` (D25), read by the caller.
#[must_use]
#[allow(clippy::too_many_lines, reason = "a verbatim port of one template")]
pub fn render_full_status(state: &InitiativeState, retire: bool) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!(
        "# {}",
        if state.slug.is_empty() {
            "(unnamed initiative)"
        } else {
            &state.slug
        }
    ));
    lines.push(String::new());
    if is_closed_initiative_status(&state.status) {
        let when = state
            .status_ts
            .as_ref()
            .map(|ts| format!(" {ts}"))
            .unwrap_or_default();
        let why = state
            .status_note
            .as_ref()
            .map(|n| format!(" — {n}"))
            .unwrap_or_default();
        let where_ = state
            .successor
            .as_ref()
            .map(|s| format!(" by {s}"))
            .unwrap_or_default();
        lines.push(format!("Status: {}{where_}{when}{why}", state.status));
        if !state.status_overrides.is_empty() {
            lines.push(format!(
                "Closed over {} finding(s):",
                state.status_overrides.len()
            ));
            for finding in &state.status_overrides {
                lines.push(format!("  - {finding}"));
            }
        }
    }
    lines.push(format!(
        "Goal: {}",
        if state.goal.is_empty() {
            "(none recorded)"
        } else {
            &state.goal
        }
    ));

    let standing = standing_constraint_lines(&state.decisions, None, retire);
    if !standing.is_empty() {
        lines.push(String::new());
        lines.extend(standing);
    }

    lines.push(format!(
        "Progress: {} across {} phase(s)",
        progress_text(task_progress(&state.phases)),
        state.phases.len()
    ));
    lines.push(String::new());

    let stale_phases = stale_active_phases(state);
    let stale_names: Vec<&str> = stale_phases.iter().map(|p| p.name.as_str()).collect();

    if !state.phases.is_empty() {
        lines.push("Phases:".to_owned());
        for phase in &state.phases {
            lines.push(format!(
                "- {} {} {}",
                phase.name,
                phase_mark(phase, &stale_names),
                phase_fraction(task_progress([phase]))
            ));
            for task in &phase.tasks {
                lines.push(format!(
                    "  - {} {} {}",
                    task_mark(&task.status),
                    task.id,
                    task.title
                ));
            }
        }
        lines.push(String::new());
    }

    lines.push(format!(
        "Next action: {}",
        state
            .current
            .next_action
            .as_deref()
            .unwrap_or("(none recorded)")
    ));

    let parallel = overlapping_writebacks(state, None);
    if !parallel.is_empty() {
        lines.push(format!("⚠ Parallel write-backs ({}):", parallel.len()));
        for w in &parallel {
            lines.push(format!(
                "- {} ({}, ended {}): {}",
                w.session_id, w.tool, w.ended, w.next_action
            ));
        }
    }

    if let Some(blocked) = &state.current.blocked_on {
        lines.push(format!("Blocked on: {blocked}"));
    }

    let last = last_with_summary(&state.sessions);

    let drift = freshness_total(&state.freshness);
    let mut staleness: Vec<String> = Vec::new();
    if drift > 0
        && let Some(ts) = &state.freshness.last_writeback_ts
    {
        staleness.push(format!(
            "- next action may be stale: {drift} event{} since the last write-back ({ts}) — {}",
            if drift == 1 { "" } else { "s" },
            describe_freshness(&state.freshness.events_since_writeback)
        ));
    }
    for sp in &stale_phases {
        staleness.push(format!(
            "- phase \"{}\": all {} tasks done but still {} — emit phase_status_changed to mark it done",
            sp.name, sp.tasks_done, sp.status
        ));
    }
    if let Some(last) = last
        && let Some(summary) = &last.summary
        && clip_detect(summary, SESSION_SUMMARY_BUDGET).1
    {
        staleness.push(format!(
            "- last write-back summary exceeds the SessionStart budget ({SESSION_SUMMARY_BUDGET} chars) and is clipped there — full text in sessions/{}.md",
            last.id
        ));
    }
    if !staleness.is_empty() {
        lines.push(String::new());
        lines.push("⚠ Staleness:".to_owned());
        lines.extend(staleness);
    }

    if !state.freshness.notes.is_empty() {
        lines.push(String::new());
        let label = if state.freshness.last_writeback_ts.is_some() {
            "Notes since write-back"
        } else {
            "Notes"
        };
        lines.push(format!("{label} ({}):", state.freshness.notes.len()));
        for n in &state.freshness.notes {
            lines.push(format!("- {} {}", n.ts, one_line(&n.text)));
        }
    }

    let conflicts = open_session_file_conflicts(state, None);
    if !conflicts.is_empty() {
        lines.push(String::new());
        lines.push(format!(
            "⚠ Concurrent edits — files touched by multiple open sessions ({}):",
            conflicts.len()
        ));
        for c in &conflicts {
            lines.push(format!("- {} (sessions {})", c.path, c.sessions.join(", ")));
        }
    }

    if let Some(last) = last {
        lines.push(String::new());
        lines.push(format!(
            "Last session ({}, ended {}):",
            last.tool,
            last.ended.as_deref().unwrap_or("?")
        ));
        lines.push(format!(
            "  {}",
            last.summary.as_deref().expect("has summary")
        ));
    }

    if !state.runs.is_empty() {
        lines.push(String::new());
        lines.push(format!(
            "Driven ({}):",
            plural(state.runs.len() as u64, "run")
        ));
        for run in &state.runs {
            lines.push(format!("- {}", describe_run(run)));
            if let Some(s) = &run.surface {
                let mut pinned: Vec<String> = Vec::new();
                if let Some(model) = surface_field(s, "model") {
                    pinned.push(format!("model {model}"));
                }
                if let Some(effort) = surface_field(s, "effort") {
                    pinned.push(format!("effort {effort}"));
                }
                lines.push(format!(
                    "  permissions: {}{}",
                    surface_field(s, "permission_mode").unwrap_or_else(|| "undefined".to_owned()),
                    if pinned.is_empty() {
                        String::new()
                    } else {
                        format!(", {}", pinned.join(", "))
                    }
                ));
                for rule in surface_list(s, "allow") {
                    lines.push(format!("    allow {rule}"));
                }
                for rule in surface_list(s, "deny") {
                    lines.push(format!("    deny {rule}"));
                }
            }
            for h in &run.handoffs {
                let task = h
                    .task
                    .as_ref()
                    .map(|t| format!(", task {t}"))
                    .unwrap_or_default();
                let tokens = h
                    .tokens
                    .map(|t| format!(", {} tokens", crate::json::number_to_string(t)))
                    .unwrap_or_default();
                let detail = h
                    .detail
                    .as_ref()
                    .map(|d| format!(" ({d})"))
                    .unwrap_or_default();
                lines.push(format!(
                    "  - {} session {} — {}{task}{tokens}{detail}",
                    h.ts, h.session_id, h.reason
                ));
            }
        }
    }

    if !state.files_touched.is_empty() {
        lines.push(String::new());
        lines.push(format!("Files touched ({}):", state.files_touched.len()));
        for file in &state.files_touched {
            lines.push(format!("- {file}"));
        }
    }

    let joined = lines.join("\n");
    format!("{}\n", joined.trim_end_matches('\n'))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fold::empty_state;

    #[test]
    fn the_cap_cuts_to_fit_with_the_marker_inside() {
        let text = "x".repeat(10_001);
        let capped = enforce_status_limit(&text);
        assert_eq!(utf16_len(&capped), STATUS_CHAR_LIMIT);
        assert!(capped.ends_with(&format!("\n{STATUS_TRUNCATION_MARKER}\n")));
        assert_eq!(enforce_status_limit("short"), "short");
        // Emoji count two units each; the cut may split one.
        let emoji = "\u{1F600}".repeat(5_001);
        let capped = enforce_status_limit(&emoji);
        assert_eq!(utf16_len(&capped), STATUS_CHAR_LIMIT);
    }

    #[test]
    fn real_alternative_detection_is_ascii_case_insensitive() {
        assert!(has_real_alternative("keep it"));
        assert!(!has_real_alternative("  "));
        assert!(!has_real_alternative("(no alternative recorded)"));
        assert!(!has_real_alternative("( NONE considered)"));
        assert!(!has_real_alternative("(\u{00A0}No Alternative"));
        assert!(has_real_alternative("(nothing)"));
        assert!(has_real_alternative("(\u{017F}one"));
    }

    #[test]
    fn empty_record_renders_the_bare_block() {
        let mut state = empty_state();
        state.slug = "demo".into();
        let out = render_status(&state, &StatusOptions::default());
        assert_eq!(
            out,
            "# Sofar status: demo\n\nGoal: (none recorded)\n\nProgress: 0/0 tasks done (0%) across 0 phase(s)\nActive phase: (none)\n\n(generated by sofar — full detail in plan.md, decisions.md, sessions/)\n"
        );
        let full = render_full_status(&state, true);
        assert_eq!(
            full,
            "# demo\n\nGoal: (none recorded)\nProgress: 0/0 tasks done (0%) across 0 phase(s)\n\nNext action: (none recorded)\n"
        );
    }

    #[test]
    fn session_line_trims_and_clips() {
        assert_eq!(session_id_line(None), None);
        assert_eq!(session_id_line(Some(" \u{FEFF} ")), None);
        assert_eq!(
            session_id_line(Some(" abc ")),
            Some(
                "Session: abc — when calling sofar_start_session, pass this as session_id.".into()
            )
        );
    }
}
