//! `cargo xtask <command>` — developer tooling for the Rust workspace.
//!
//! `schema [--check]`: step 2 of the codegen pipeline (rust-core 2.1, D1,
//! D9). Reads `crates/sofar-schema/schema/events.schema.json` (emitted from
//! `packages/schema/src/events.ts` by `npm run schema:emit`), generates Rust
//! types with typify, formats them with the toolchain's rustfmt and writes
//! `crates/sofar-schema/src/generated.rs`. With `--check` it writes nothing
//! and exits 1 when the committed file differs — the CI regen-diff.

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

use typify::{TypeSpace, TypeSpaceSettings};

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is xtask/; the workspace is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits inside the workspace")
        .to_path_buf()
}

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    if args.next().as_deref() != Some("schema") {
        eprintln!("usage: cargo xtask schema [--check]");
        return ExitCode::from(64);
    }
    let check = args.any(|a| a == "--check");
    match schema(check) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("xtask schema: {e}");
            ExitCode::from(2)
        }
    }
}

const HEADER: &str = "\
// GENERATED by `cargo xtask schema` from crates/sofar-schema/schema/events.schema.json,
// itself emitted from packages/schema/src/events.ts by `npm run schema:emit`.
// Do not edit: change the TypeScript, regenerate, review the diff (rust-core D1).
";

fn schema(check: bool) -> Result<ExitCode, Box<dyn std::error::Error>> {
    let root = workspace_root();
    let schema_path = root.join("crates/sofar-schema/schema/events.schema.json");
    let out_path = root.join("crates/sofar-schema/src/generated.rs");

    let text = std::fs::read_to_string(&schema_path)
        .map_err(|e| format!("{}: {e}", schema_path.display()))?;
    let root_schema: schemars::schema::RootSchema = serde_json::from_str(&text)?;

    let mut settings = TypeSpaceSettings::default();
    settings
        .with_derive("PartialEq".to_owned())
        .with_derive("Eq".to_owned())
        .with_struct_builder(false);
    let mut space = TypeSpace::new(&settings);
    space.add_root_schema(root_schema)?;

    let body = rustfmt(&space.to_stream().to_string())?;
    let generated = format!("{HEADER}\n{body}");

    let current = std::fs::read_to_string(&out_path).unwrap_or_default();
    if check {
        if current == generated {
            println!("fresh: {}", out_path.display());
            return Ok(ExitCode::SUCCESS);
        }
        eprintln!(
            "stale: {} differs from the schema — run `cargo xtask schema`",
            out_path.display()
        );
        return Ok(ExitCode::FAILURE);
    }
    if current == generated {
        println!("unchanged: {}", out_path.display());
    } else {
        std::fs::write(&out_path, generated)?;
        println!("wrote {}", out_path.display());
    }
    Ok(ExitCode::SUCCESS)
}

/// Format with the pinned toolchain's rustfmt (rust-toolchain.toml), so the
/// committed file is stable across machines.
fn rustfmt(source: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--quiet"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()?;
    child
        .stdin
        .take()
        .expect("piped stdin")
        .write_all(source.as_bytes())?;
    let out = child.wait_with_output()?;
    if !out.status.success() {
        return Err(format!("rustfmt exited with {}", out.status).into());
    }
    Ok(String::from_utf8(out.stdout)?)
}
