//! Event payload types for sofar's native core.
//!
//! Everything in [`generated`] is produced from `packages/schema/src/events.ts`
//! by the two-step pipeline `npm run schema:emit` (TypeScript → JSON Schema)
//! and `cargo xtask schema` (JSON Schema → Rust via typify), and is committed
//! so a build never runs a generator. Hand-editing it is a contract break
//! (rust-core D1): change the TypeScript, regenerate, review the diff.
//!
//! Validation RULES (a `note` required when a status is `dropped`, a `guard`
//! needing its `rule`, integer ranges) are logic, not shape; they are ported
//! by hand in `sofar-core` and proven by the conformance suite, exactly as the
//! guard grammar is.

#[allow(
    clippy::all,
    clippy::pedantic,
    missing_debug_implementations,
    rustdoc::all,
    reason = "generated by typify; formatting and idiom belong to the generator"
)]
#[rustfmt::skip]
pub mod generated;

pub use generated::*;
